### ISSUE TITLE
Composer error after installation

### ISSUE THREAD

**Issue by r-hoffmann** [simonhamp/ensemble-plugin#1]
I have created an account on the website and followed the installation steps. Everything was easy and no errors occured. However, something goes wrong when the route /ensemble is called. 

The following error is 4 times in my log files with 5 minutes between them. The Laravel 5.6 application is running on an ordinary VPS with Ubuntu 16.04. If you need more information or if I can contribute in some way, please let me know.

```[2018-06-15 19:30:03] local.ERROR: The command "'/usr/local/bin/composer' 'outdated' '--format=json' '--all'" failed.

Exit Code: 1(General error)

Working directory: /var/www/potje

Output:
================


Error Output:
================

                                                                                            
  [RuntimeException]                                                                        
  The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly  
                                                                                            

 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"'/usr/local/bin/composer' 'outdated' '--format=json' '--all'\" failed.

Exit Code: 1(General error)

Working directory: /var/www/potje

Output:
================


Error Output:
================

                                                                                            
  [RuntimeException]                                                                        
  The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly  
                                                                                            

 at /var/www/potje/vendor/simonhamp/ensemble-plugin/src/PackageChecker.php:28)
[stacktrace]
#0 /var/www/potje/vendor/simonhamp/ensemble-plugin/src/EnsembleServiceProvider.php(44): SimonHamp\\Ensemble\\PackageChecker::getJson(Array)
#1 /var/www/potje/vendor/simonhamp/ensemble-plugin/src/EnsembleServiceProvider.php(83): SimonHamp\\Ensemble\\EnsembleServiceProvider->SimonHamp\\Ensemble\\{closure}()
#2 /var/www/potje/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(327): SimonHamp\\Ensemble\\EnsembleServiceProvider->SimonHamp\\Ensemble\\{closure}()
#3 /var/www/potje/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(304): Illuminate\\Cache\\Repository->remember('ensemble_all', 60, Object(Closure))
#4 /var/www/potje/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#5 /var/www/potje/vendor/simonhamp/ensemble-plugin/src/EnsembleServiceProvider.php(84): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#6 /var/www/potje/vendor/simonhamp/ensemble-plugin/src/EnsembleServiceProvider.php(45): SimonHamp\\Ensemble\\EnsembleServiceProvider->payload('ensemble_all', Object(Closure))
#7 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): SimonHamp\\Ensemble\\EnsembleServiceProvider->SimonHamp\\Ensemble\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Route.php(172): Illuminate\\Routing\\Route->runCallable()
#9 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#10 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/potje/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#14 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#15 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#16 /var/www/potje/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#17 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/potje/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/potje/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/potje/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/potje/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/potje/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/potje/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/potje/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/potje/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/potje/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/potje/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/potje/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/potje/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/potje/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /var/www/potje/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#36 /var/www/potje/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#37 {main}
"}

**Comment by simonhamp** [comment]
@r-hoffmann apologies for the late reply, I didn't get an alert about your issue from GitHub for some reason :/

How is Composer installed on your production server? Do you know its location?

This looks like a misconfiguration in Composer. Can you run any Composer commands directly on your server successfully?

**Comment by simonhamp** [comment]
@r-hoffmann when you get chance, please could you update to [v1.2.0](https://github.com/simonhamp/ensemble-plugin/releases/tag/v1.2.0) and get Ensemble to try polling your app again?

In your Ensemble dashboard, click `Details` under to the relevant app, then `Reset and try again` at the top.

**Comment by r-hoffmann** [comment]
@simonhamp Sorry for not replying to your messages. I saw that you were working on it and waited for the merge. I just did what you said, let's see what happens!

**Comment by simonhamp** [comment]
@r-hoffmann apologies for the late reply. Any news?
